Addition of two examples to SchedulingIntegrationTests to illustrate …
NASA-AMMOS/aerie pull request #1090
Opened 2023-08-11 00:45 UTC by jmdelfa

…how to model a unitary goal.

* **Tickets addressed:** AERIE-000
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

## Verification

## Documentation

## Future work

2023-08-23 17:20 UTC, adrienmaillard commented
@jmdelfa I was reading these tests and I felt bad for our users having to do all the boilerplate with Windows and Interval so I made another commit to your branch adding the possibility for the user to give Interval or Temporal.Instant directly to CoexistenceGoal and then we do the conversion ourselves. I have also modified the examples you gave.

2023-08-23 17:22 UTC, adrienmaillard commented
The only downside for you is that you would have to write more documentation to show these use-cases to the user :)

2023-08-23 21:08 UTC, jmdelfa commented
I agree with the modifications proposed by @adrienmaillard

2023-08-29 02:04 UTC, mattdailis requested changes

2023-08-29 02:04 UTC, mattdailis commented on scheduler-worker/scheduling-dsl-compiler/src/libs/scheduler-edsl-fluent-api.ts
> +    }
Here are the spaces you and I discussed adding - it doesn't look to me like they made it into the final version

```suggestion
    if (opts.forEach instanceof WindowsEDSL.Interval) {
      localForEach = Windows.Value(true, opts.forEach).assignGaps(false);
    } else if (opts.forEach instanceof Temporal.Instant) {
      localForEach = Windows.Value(true,Interval.At(opts.forEach)).assignGaps(false);
    } else {
      localForEach = opts.forEach;
    }
```

2023-08-30 21:48 UTC, jmdelfa commented on scheduler-worker/scheduling-dsl-compiler/src/libs/scheduler-edsl-fluent-api.ts
> +    }
Updated code with spacing included

2023-08-30 21:53 UTC, mattdailis approved these changes

2023-08-30 21:58 UTC, mattdailis approved these changes

2023-08-30 22:00 UTC, mattdailis approved these changes

2023-08-30 22:13 UTC, jmdelfa commented
All comments resolved. PR ready to be merged

2023-08-30 22:21 UTC, adrienmaillard commented
WOW, triple approval, this must mean something :-) 
![Screenshot 2023-08-30 at 3 20 18 PM](https://github.com/NASA-AMMOS/aerie/assets/94930916/e5e2d50e-2413-4372-b73b-edfef0b0d089)

2023-08-30 23:17 UTC, merged