Add `created_by` column to `activity_directive`
NASA-AMMOS/aerie pull request #1181
Opened 2023-10-04 23:50 UTC by skovati

* **Tickets addressed:** closes #1176
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description
Adds a new column, `created_by`, to `activity_directive`, which is automatically populated by a hasura session. This field is nullable and will be empty for all existing activity directives.

## Verification
Manual testing mostly (e.g. check field is copied during plan merge / snapshot) as the change itself is simple. Relying on database migration tests for verification.

## Documentation
N/A

## Future work
Not a particular piece of work, but I'll note that changing relatively simple things like this in the database is quite painful atm, as several different stored procedures directly reference tables like `activity_directive`, so a developer needs to keep a mental list of these and what changes need to be made. This is especially quirky with database migrations, since we need to copy paste procedures just to change one line, which is what ~1400 lines of this PR is.

2023-10-05 19:36 UTC, Mythicaeda requested changes
DBTests need to be updated. I know for sure off the top of my head that `Activity` and `SnapshotActivity` in `PlanCollaborationTests` need to be updated, as well as the method `assertActivityEquals`, and any tests that check that do Equivalency checks but can't use that method (ie, the test `snapshotCapturesAllActivities`, which is comparing between a `SnapshotActivity` and an `Activity`)

2023-10-09 19:33 UTC, skovati commented
@Mythicaeda DB tests have been updated

2023-10-12 22:44 UTC, Mythicaeda commented on db-tests/src/test/java/gov/nasa/jpl/aerie/database/PlanCollaborationTests.java
> +        assertEquals(planActivities.get(i).createdBy, snapshotActivities.get(i).createdBy);
This check also needs to be added in `assertActivitiesEquals` (L524)

2023-10-13 16:52 UTC, skovati commented on db-tests/src/test/java/gov/nasa/jpl/aerie/database/PlanCollaborationTests.java
> +        assertEquals(planActivities.get(i).createdBy, snapshotActivities.get(i).createdBy);
Change has been made!

2023-10-13 19:05 UTC, Mythicaeda reviewed
:shipit:

2023-10-13 19:05 UTC, Mythicaeda approved these changes

2023-10-13 19:34 UTC, merged