[FIX] Stricter/more correct type checking
NASA-AMMOS/aerie pull request #158
Opened 2022-04-29 20:45 UTC by dyst5422

* **Tickets addressed:** NA
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

There is an issue that was identified while working on the constraint dsl. The typescript type system is structural type system and not a nominal type system. A strange side effect of this is that almost anything can be assigned to `{}` since everything in JS is an object. Anything sufficiently implements the interface `{}`.

Skip to our classes used for the EDSL - if they don't have public methods on them, then they are effectively the empty type `{}`. A user could return a number and the type checker would be fine with it.

So we thought about it from the structural interface standpoint and asked ourselves "What does something the user returns need to have to be valid". The answer is some way to generate an Abstract Syntax Tree node. In order to type check that, it needs to be publicly visible. So our previous attempts to hide the ast node in the background of the EDSL classes is actually counterproductive. We made the ast node `public readonly` and renamed it to `__astNode` to make clear that it is an internal property only and isn't part of the user api. We could then remove the serialize method as it was unnecessary.

## Verification

Pre-existing tests are all passing

## Documentation

No documentation need for this change

## Future work

2022-04-29 21:47 UTC, JoelCourtney approved these changes

2022-04-29 21:56 UTC, JoelCourtney commented on scheduler-server/scheduling-dsl-compiler/src/main.ts
>      // here to deserialize the Goal due to different evaluation contexts
This comment probably needs to be updated.

2022-04-29 23:04 UTC, pcrosemurgy approved these changes

2022-05-02 22:17 UTC, mattdailis requested changes
Looks good to me - I'm a bit fuzzy on how classes work in terms of structural subtyping. What I'm inferring from this change is that if a field is public, it is considered part of the type, and if it's private, it isn't considered part of the type.

The only thing I'd request for this PR is that we add a test that would have failed before this change.

2022-05-05 16:24 UTC, mattdailis approved these changes
Thanks for adding the test! Looks good to me.

2022-05-05 16:35 UTC, merged