[AERIE-1847]  Add duration filter to constraints eDSL
NASA-AMMOS/aerie pull request #185
Opened 2022-05-26 13:06 UTC by adrienmaillard

* **Tickets addressed:** AERIE-1847
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

This is building on top of #179.

I have reimplemented the filters in the constraints library. 

## Verification

Several tests have been written/modified. 

## Documentation

Some documentation about these new filters should be added to the wiki.

## Future work

All of the other filters/transformers.

2022-06-09 03:05 UTC, mattdailis approved these changes
Looks like there are some extra files (`README` and `windows-edsl-fluent-api.ts`), but I _think_ they'll disappear after a rebase. If not, we should delete them.

Looks good to me! I'm wondering if in the DSL fluent API, if there's any clearer word than "longerThan". I'm thinking along the lines of `forADurationOfAtLeast` and `forADurationOfAtMost` (too long, I know 😝 )

Here's how it would look with `forLongerThan`:
```typescript
Real.Resource("state of charge").rate().equal(Real.Value(4.0)).forLongerThan(1000)
```
it reads well in that example, but I'm not sure if it will make grammatical sense in all cases 🤷 . Just brainstorming, I'm happy to leave the names as is and rename them if ever we decide we've found better ones.

2022-06-09 03:05 UTC, mattdailis commented on merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
> +  public longerThan(duration: number) : Windows {
Let's use the Duration type for durations (even though it is currently aliased to `number`)

```suggestion
  public longerThan(duration: Duration) : Windows {
```

2022-06-09 03:05 UTC, mattdailis commented on merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
> +  public shorterThan(duration: number) : Windows {
```suggestion
  public shorterThan(duration: Duration) : Windows {
```

2022-06-09 03:05 UTC, mattdailis commented on merlin-server/constraints-dsl-compiler/src/libs/constraints-edsl-fluent-api.ts
> +    public shorterThan(duration: number): Windows;
```suggestion
    public longerThan(duration: Duration): Windows;
    public shorterThan(duration: Duration): Windows;
```

2022-06-09 09:07 UTC, adrienmaillard commented
Weird stuff: the branch has been rebased onto develop, then forced-pushed. On my side, the branch is clean, only containing my 3 commits. Still got a small part of 4 of commits from your branch.

2022-06-09 09:16 UTC, adrienmaillard commented
If we change the names, I'd be in favor of your longer option with `duration` inside the name to make clear we go from the resource domain to the window domain.

2022-06-09 15:19 UTC, goetzrrGit approved these changes

2022-06-09 22:42 UTC, patkenneally requested changes
Has the documentation been updated? If/when it has please update the PR description and we can merge.

2022-06-13 07:08 UTC, adrienmaillard commented
@patkenneally done.

2022-06-15 21:39 UTC, patkenneally approved these changes

2022-06-16 08:58 UTC, merged