[AERIE-1879] Commands with Dynamic Repeating Arguments are Out of Order
NASA-AMMOS/aerie pull request #210
Opened 2022-06-08 18:19 UTC by goetzrrGit

* **Tickets addressed:** AERIE-1879
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

**NOTE: You will need https://github.com/NASA-AMMOS/aerie/pull/194 merged in order to run the JEST test. There is a bug with absolute time that the PR is addressing and JEST is using** 

Clipper has special commands with dynamic repeating arguments. 

ex.
`SEQ_VAR_CMD( [dynamic_arg -> n]..., opcode);`

The above command can be written below

```
SEQ_VAR_CMD( dynamic_arg1, opcode);
SEQ_VAR_CMD( dynamic_arg1, dynamic_arg2, dynamic_arg3, opcode);
SEQ_VAR_CMD( dynamic_arg1, dynamic_arg2, dynamic_arg3, dynamic_arg4, dynamic_arg5, opcode);
etc.
```

The command dictionary typescript library generator already handles these special commands, but with Javascript's `Objects` ordering is not guaranteed so we need to preserve the order of these dynamic arguments. 

Here is an example with a new bananantion command - `PACKAGE_BANANA`

```
    // arguments in order 
    PACKAGE_BANANA({
        bundle_name1: "Chiquita",
        number_of_bananas1: 43,
        bundle_name2: "Dole",
        number_of_bananas2: 12,
        lot_number: 1093,
      }),
      
      // arguments are out of order
      PACKAGE_BANANA({
        bundle_name2: "Dole",
        number_of_bananas1: 43,
        bundle_name1: "Chiquita",
        lot_number: 1093,
        number_of_bananas2: 12
      })
```

When you expand a sequence you should have the arguments for the command in the correct order.

```
   {
      type: 'command',
      stem: 'PACKAGE_BANANA',
      time: { type: 'COMMAND_COMPLETE' },
      args: ['Chiquita', 43, 'Dole', 12, 1093],
      metadata: { simulatedActivityId: simulatedActivityId4 },
    },

    {
      type: 'command',
      stem: 'PACKAGE_BANANA',
      time: { type: 'COMMAND_COMPLETE' },
      args: ['Chiquita', 43, 'Dole', 12, 1093],
      metadata: { simulatedActivityId: simulatedActivityId4 },
    },
```

## Verification
Ran through this by hand and also used the JEST tester

## Documentation

## Future work

2022-06-08 20:17 UTC, dyst5422 requested changes

2022-06-08 20:17 UTC, dyst5422 commented on command-expansion-server/src/lib/codegen/CommandEDSLPreface.ts
> +  for (let i = 0; i < argumentOrders.length; i++) {
Use for...of instead

2022-06-08 20:17 UTC, dyst5422 commented on command-expansion-server/src/lib/codegen/CommandTypeCodegen.ts
> +              return `"${arg.name}${n}"`;
No need of a new scope/return here

```
arg => `"${arg.name}${n}"
```

2022-06-08 20:17 UTC, dyst5422 commented on command-expansion-server/src/lib/codegen/CommandTypeCodegen.ts
> +            return `"${arg.name}"`;
Same as above comment

2022-06-08 23:20 UTC, goetzrrGit commented on command-expansion-server/src/lib/codegen/CommandEDSLPreface.ts
> +  for (let i = 0; i < argumentOrders.length; i++) {
Thanks for the suggestion

2022-06-08 23:20 UTC, goetzrrGit commented on command-expansion-server/src/lib/codegen/CommandEDSLPreface.ts
> +  for (let i = 0; i < argumentOrders.length; i++) {
Thanks for the suggestion

2022-06-08 23:20 UTC, goetzrrGit commented on command-expansion-server/src/lib/codegen/CommandTypeCodegen.ts
> +              return `"${arg.name}${n}"`;
Thanks for the suggestion

2022-06-08 23:20 UTC, goetzrrGit commented on command-expansion-server/src/lib/codegen/CommandTypeCodegen.ts
> +              return `"${arg.name}${n}"`;
Thanks for the suggestion

2022-06-08 23:20 UTC, goetzrrGit commented on command-expansion-server/src/lib/codegen/CommandTypeCodegen.ts
> +            return `"${arg.name}"`;
Thanks for the suggestion

2022-06-08 23:20 UTC, goetzrrGit commented on command-expansion-server/src/lib/codegen/CommandTypeCodegen.ts
> +            return `"${arg.name}"`;
Thanks for the suggestion

2022-06-13 21:16 UTC, pcrosemurgy approved these changes
Nice work Ryan! All tests passing for me locally.

As part of this PR I would strongly suggest working around / fixing the timeout test failure that occurs upon the first run of `npm run test`. I think that it's okay if our command expansion server tests are not fully automated but they should at least be deterministic (in the sense that both the 1st and 2nd runs yield the same results).

Not going to hold this PR up over this so I'll let you decide if you want to tackle that here or not.

2022-06-15 17:59 UTC, mattdailis commented on command-expansion-server/src/lib/codegen/CommandTypeCodegen.ts
> +const ${fswCommandName}_ARGS_ORDERS = [${argsOrder.join(',')}];
Double checking - is the `_ARGS_ORDERS` (with the `S` on the end) correct? Elsewhere I seem to recall seeing `_ARGS_ORDER` singular 🤔

2022-06-15 18:08 UTC, dyst5422 commented on command-expansion-server/src/lib/codegen/CommandTypeCodegen.ts
> +const ${fswCommandName}_ARGS_ORDERS = [${argsOrder.join(',')}];
Concur, it should be without an `S`

2022-06-15 18:09 UTC, dyst5422 commented on command-expansion-server/src/lib/codegen/CommandTypeCodegen.ts
> +const ${fswCommandName}_ARGS_ORDERS = [${argsOrder.join(',')}];
Actually, I think it is because this is fundamentally different since there are many valid argument orderings. So the `S` designates that difference

2022-06-15 18:11 UTC, goetzrrGit commented on command-expansion-server/src/lib/codegen/CommandTypeCodegen.ts
> +const ${fswCommandName}_ARGS_ORDERS = [${argsOrder.join(',')}];
This data structure is a list of argument order so I made it an 's' for this one.

2022-06-21 16:20 UTC, dyst5422 approved these changes

2022-06-21 16:34 UTC, merged