[Investigate] AERIE-1824 - Rework TimeType API
NASA-AMMOS/aerie pull request #241
Opened 2022-07-11 22:55 UTC by goetzrrGit

* **Tickets addressed:** AERIE-1824
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description
I Prototype a different way to specify time values. The code works, but I need to clean up and figure out why this [line](https://github.com/NASA-AMMOS/aerie/compare/feature/AERIE-1824--Refactor-Time-Type-edsl?expand=1#diff-224d12ae69810ebad6855e95127d0a73a31d2653d5207744b5f8f68370bc0727R94) `type Commands` doesn't provide method signatures to the Authoring Logic. For now I am using `aaType` which is identical to `Commands` in [CommandTypeCodgen](https://github.com/NASA-AMMOS/aerie/compare/feature/AERIE-1824--Refactor-Time-Type-edsl?expand=1#diff-664406c819e249960325a4124e84cd5c9f675976870b5a8e5c7a92ad6cf9ea73R36)

I also reworked how we define commands with dynamic arguments. The original version doesn't support this new style. 

Original way:

```
<command>.absoluteTiming(Temporal.instance)
<command>.relativeTiming(Temporal.duration)
<command>.epochTiming(Temporal.duration)
<command>
```

example:

```
ADD_WATER.absoluteTiming(Temporal.Instant.from("2022-04-20T20:17:13Z"))
EAT_BANANA.relativeTiming(Temporal.Duration.from({ minutes: 15, seconds: 30 }))
PREPARE_LOAF(1,true).relativeTiming(Temporal.Duration.from({ minutes: 15, seconds: 30 }))
```

The original way isn't too bad but there was some feedback from Basak that it would be better for our users to write it below:

A(DOYTime).command
R(duration).command
E(duration)command
C.command or command

example:

```
A("2020-060T03:45:19").ADD_WATER
R(00:15:00)EAT_BANANA
E(00:15:30).PREPARE_LOAF(1,true)
C.BAKE_BREAD

```

**PROS and CONS of the new approach**

Pros: 

- Simpler: The user doesn't have to specify a temporal time anymore as the method will try to convert the string time into a temporal value. Temporal time is still accepted
- Readability is better 

Cons:

- Lose of auto-helper

New:
<img width="794" alt="Screen Shot 2022-07-11 at 12 22 09 PM" src="https://user-images.githubusercontent.com/70245883/178368571-e5edb673-deaf-4bc0-8a35-2f11c1863be9.png">

Old:
<img width="780" alt="Screen Shot 2022-07-11 at 12 23 15 PM" src="https://user-images.githubusercontent.com/70245883/178368709-a538b810-6bcb-41e0-b909-300e18ad4c20.png">

The new approach loses the variable names and the description of the command. I did a lot of digging in typescript and I couldn't find a way to add them back. Comments from Stack Overflow mentioned that there isn't a way to preserve function arguments name when using `Parameter` Util

As of now, I am not sure if we want to move on with this approach and probably need to discuss this with the team further. I admit that my approach might not be the best way to accomplish this and would like some feedback. 

## Verification
All JEST Test Pass

## Documentation
If we move forward I will update the documentation for Command Authoring

## Future work
Add more helper methods to make authoring easier.

2022-07-11 23:32 UTC, dyst5422 requested changes
I think we can make it a bit more terse using tagged template literals https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates
so we can write it like
```typescript
A`2020-060T03:45:19`.ADD_WATER
R`00:15:00`.EAT_BANANA
E`00:15:30`.PREPARE_LOAF(1,true)
```

We would then support supplying a value that isn't a string using overloads so we can properly type check the variadic inputs.

EX:

```typescript

function A(...args: [TemplateStringsArray, ...string[]]): GeneratedCommands;
function A(timeVal: Temporal.Instant): GeneratedCommands;
function A(timeDOYString: string): GeneratedCommands;
function A(...args: [TemplateStringsArray, ...string[]] | [Temporal.Instant] | [string]): GeneratedCommands {
  let timeVal = timeValue;
  // Handle tagged template format
  if (Array.isArray(args[0])) {
    timeVal = Command.doyToInstant(String.raw(args));
  }
  // Handle string inputs
  else if (typeof args[0] === 'string') {
    timeVal = Command.doyToInstant(args[0]);
  }

  ...do rest of stuff now that we've normalized the time value to a Temporal.Instant


}
```

This allows us to use it in all of the following ways with strong checking

```typescript
A`2020-060T03:45:19`.ADD_WATER

let doyString = '2020-060T03:45:19';
A(doyString).ADD_WATER

let temporalInstant = doyToInstant('2020-060T03:45:19');
A(temporalInstant).ADD_WATER
```

2022-07-11 23:32 UTC, dyst5422 commented on command-expansion-server/src/lib/codegen/CommandEDSLPreface.ts
> +      absoluteTime: String | Temporal.Instant;
String is not something you should generally use see https://dev.to/josiasaurel/the-difference-between-string-and-string-in-typescript-4mf2

2022-07-11 23:32 UTC, dyst5422 commented on command-expansion-server/src/lib/codegen/CommandEDSLPreface.ts
> +                  ? Command.doyToInstant(this.absoluteTime as DOY_STRING)
We should do this conversion in the time functions themselves (A,R,E)

2022-07-11 23:32 UTC, dyst5422 commented on command-expansion-server/src/lib/codegen/CommandEDSLPreface.ts
> +function commandsWithTimeValue(
We can better type this as
```typescript
function commandsWithTimeValue<T extends TimingTypes>(
  timeValue: T extends TimingTypes.Absolute ? string | Temporal.Instant : string | Temporal.Duration,
  timeType: T
): GeneratedCommands
```

This allows us to enforce that absolute uses strings or instants and relative uses strings or durations

2022-07-13 15:55 UTC, dyst5422 requested changes

2022-07-13 15:55 UTC, dyst5422 commented on command-expansion-server/src/lib/codegen/CommandEDSLPreface.ts
> +  // @ts-ignore : 'Commands' found in generated code
Love the comments here

2022-07-13 15:55 UTC, dyst5422 commented on command-expansion-server/src/lib/codegen/CommandEDSLPreface.ts
> +  public static hmsToDuration(hms: HMS_STRING): Temporal.Duration {
I think we may want to separate these conversions into their own non-exported functions so that they don't become part of the public API?

2022-07-19 16:53 UTC, dyst5422 commented on command-expansion-server/src/lib/codegen/CommandEDSLPreface.ts
> +  public static hmsToDuration(hms: HMS_STRING): Temporal.Duration {
@goetzrrGit ☝️

2022-07-19 17:57 UTC, goetzrrGit commented on command-expansion-server/src/lib/codegen/CommandEDSLPreface.ts
> +  public static hmsToDuration(hms: HMS_STRING): Temporal.Duration {
Oh I didn't see this. I will look at this now.

2022-07-19 18:19 UTC, goetzrrGit commented on command-expansion-server/src/lib/codegen/CommandEDSLPreface.ts
> +  public static hmsToDuration(hms: HMS_STRING): Temporal.Duration {
I pulled the out in the last commit.

2022-07-19 20:52 UTC, dyst5422 approved these changes
LGTM

2022-07-26 16:18 UTC, camargo approved these changes

2022-07-26 16:53 UTC, merged