Upgrade seq-json-schema in sequencing server to use 1.0.17
NASA-AMMOS/aerie pull request #733
Opened 2023-03-14 19:39 UTC by camargo

* **Tickets addressed:** Resolves https://github.com/NASA-AMMOS/aerie/issues/728
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description

Updates to the latest seq-json-schema

2023-03-15 17:50 UTC, goetzrrGit requested changes
For the most part, it looks great. Just curious about nested repeating args. The original function used recursion to handle that extremely rare case.

2023-03-15 17:50 UTC, goetzrrGit commented on sequencing-server/src/lib/codegen/CommandEDSLPreface.ts
> +            return this.convertRepeatArgs(arg);
What if the repeating arguments have nested repeating arguments? We probably want to have some recursion for that.

2023-03-15 18:36 UTC, camargo commented on sequencing-server/src/lib/codegen/CommandEDSLPreface.ts
> +            return this.convertRepeatArgs(arg);
So actually we are not supporting nested repeat arguments because the AMPCS command dictionary does not support them

2023-03-16 14:52 UTC, cohansen approved these changes
Looks great to me, thanks for adding the changes to the EDSL (I thought I caught everything) and fixing the tests!

2023-03-16 18:06 UTC, goetzrrGit approved these changes

2023-03-16 18:10 UTC, merged