Assign zero duration to activities with no effect model
NASA-AMMOS/aerie pull request #911
Opened 2023-05-04 20:07 UTC by JoelCourtney

* **Tickets addressed:** inspired by #908 
* **Review:** By commit  
* **Merge strategy:** Merge (no squash)  

## Description
For activities that have no effect model, we should default to assigning `FixedDuration(ZERO)` instead of uncontrollable.

## Verification
Banananananation's ParameterTest activity's generated code was changed by this PR. Given that we have tests for FixedDuration, and tests that use ParameterTest, I'm satisfied not adding any new tests.

2023-05-08 17:22 UTC, camargo approved these changes
Looks reasonable to me

2023-05-09 20:20 UTC, mattdailis requested changes
Just a slightly more idiomatic way to express this in JavaPoet - the change itself looks great, I'm glad it was this straightforward.

2023-05-09 20:20 UTC, mattdailis commented on merlin-framework-processor/src/main/java/gov/nasa/jpl/aerie/merlin/processor/generator/MissionModelGenerator.java
> +                                                          .orElse(CodeBlock.of("fixed(gov.nasa.jpl.aerie.merlin.protocol.types.Duration.ZERO)"))))
```suggestion
                                                          .orElse(CodeBlock.of("fixed($T.ZERO)", ClassName.get(Duration.class)))))
```

2023-05-10 14:47 UTC, mattdailis approved these changes
:rocket:

2023-05-11 18:34 UTC, merged